name: Get File

on:
  workflow_dispatch:
    inputs:
      query:
        description: 'Search query'
        required: false
        type: string
      environment:
        description: 'Select the target environment'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - qa
          - prod

jobs:
  call-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Call Verint API
        env:
          API_BASE_URL: ${{ secrets[format('VERINT_BASE_URL_{0}', inputs.environment)] }}
          API_USERNAME: ${{ secrets.VERINT_USERNAME }}
          API_PASSWORD: ${{ secrets.VERINT_PASSWORD }}
        run: |
          QUERY="${{ github.event.inputs.query || 'index' }}"
          
          echo "Making API call to the ${{ inputs.environment }} environment with parameters:"
          echo "Query: $QUERY"
          
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" \
            -X 'GET' \
            "${API_BASE_URL}/files?query=${QUERY}" \
            -H 'accept: application/json' \
            -u "${API_USERNAME}:${API_PASSWORD}")
          
          http_code=$(echo $response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          body=$(echo $response | sed -E 's/HTTPSTATUS\:[0-9]{3}$//')
          
          echo "HTTP Status Code: $http_code"
          echo "Response Body: $body"
          
          if [ $http_code -eq 200 ]; then
            echo "✅ API call successful!"
            echo "Response saved to api_response.json"
            echo "$body" > api_response.json
          else
            echo "❌ API call failed with status code: $http_code"
            exit 1
          fi
      
      - name: Upload response as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: api-response
          path: api_response.json
          retention-days: 7
